baseURL = "https://gohugo.io/"
title = "Hugo Themes"
author = "Steve Francia"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-12345678-0"
disqusShortname=""
copyright = "&copy;Qiushi Pan 2018-2019"

[params]
description = "Hugo-Primer theme's example site"
twitter = ""
useIcon = false
useTwitterCard = true
shareTo = ["Twitter", "Hatena", "Facebook", "Pocket"]
showFooterCredits = true
math = true
